# Generated by Django 6.0.4 on 2026-05-05 09:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='pengemudi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanan_diambil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('penumpang', 'Penumpang'), ('pengemudi', 'Pengemudi'), ('penyedia', 'Penyedia Layanan')], default='penumpang', max_length=15),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='status',
            field=models.CharField(choices=[('Menunggu Pengemudi', 'Menunggu Pengemudi'), ('Sedang Diantar', 'Sedang Diantar'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Menunggu Pengemudi', max_length=25),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ulasan', models.TextField(blank=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('pengemudi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_diterima', to=settings.AUTH_USER_MODEL)),
                ('penumpang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_diberikan', to=settings.AUTH_USER_MODEL)),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='main.pesanan')),
            ],
        ),
    ]
